const VideosActionTypes = {
  FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
  FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_VIDEO_TO_WATCH: 'SET_VIDEO_TO_WATCH',
};

export default VideosActionTypes;
