const VideosActionTypes = {
  FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
  FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',
  SET_SELECTED_VIDEO: 'SET_SELECTED_VIDEO',
};

export default VideosActionTypes;
