export const suggestedSearchesElements = [
  'alan walker',
  'ariana grande',
  'asmr',
  'avengers endgame',
  'baby shark',
  'bad bunny',
  'badabun',
  'billie eilish',
  'blackpink',
  'borderlands 3',
  'bts',
  'cnn',
  'dantdm',
  'diresta tool drawer',
  'espn',
  'fortnite',
  'fox news',
  'game grumps',
  'jacksepticeye',
  'justice league',
  'lofi',
  'mantis shrimp',
  'markiplier',
  'minecraft',
  'msnbc',
  'music',
  'musica',
  'naturo',
  'ninja',
  'nintendo',
  'old town road',
  'peliculas completas en español',
  'peppa pig',
  'pewdiepie vs t series',
  'pewdiepie',
  'roblox',
  'senorita',
  'tik tok',
  'try not to laugh',
  'ufc',
  'wintergatan marble machine',
  'wwe',
];
