const AUTH_STORAGE_KEY = 'wa_cert_authenticated';
const VIDEO_STORAGE_KEY = 'VIDEO_KEY';
const USER_PREFERENCES_STORAGE_KEY = 'USER_PREFERENCES';

export { AUTH_STORAGE_KEY, VIDEO_STORAGE_KEY, USER_PREFERENCES_STORAGE_KEY };
