const ACTIONS = {
  FETCH_VIDEOS: 'FETCH_VIDEOS',
  FETCH_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_ERROR: 'FETCH_VIDEOS_ERROR',
  CURRENT_VIDEO: 'CURRENT_VIDEO',
  ADD_FAVORITES: 'ADD_FAVORITES',
  REMOVE_FAVORITES: 'REMOVE_FAVORITES',
};

export { ACTIONS };
