const actions = {
  SET_VIDEOS: 'SET_VIDEOS',
  ADD_VIDEOS: 'ADD_VIDEOS',
  SET_THEME: 'SET_THEME',
  TOGGLE_THEME: 'TOGGLE_THEME',
  SET_CURRENT_VIDEO: 'SET_CURRENT_VIDEO',
  TOGGLE_NAV: 'TOGGLE_NAV',
  SET_USER: 'SET_USER',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
};
export default actions;
